---
- name: Install curl
  apt:
    name: curl
    state: present

- name: Add MaxScale repositories
  shell: curl -sS https://downloads.mariadb.com/MariaDB/mariadb_repo_setup | sudo bash

- name: Install MaxScale
  apt:
    name: maxscale
    state: present

- name: Config MaxScale
  template:
    src: maxscale.cnf.j2
    dest: /etc/maxscale.cnf
  notify: restart MaxScale
